# Generated by Django 3.2 on 2022-05-17 11:04

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z]+(?:,\\[a-zA-Z]+)*\\Z'), code='invalid', message='Enter only comma separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
