# Generated by Django 3.2 on 2022-05-17 13:00

import django.core.validators
from django.db import migrations, models
import f_hlis.post.utils
import re


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220517_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=f_hlis.post.utils.get_post_photo_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='hash_tag',
            field=models.CharField(blank=True, max_length=256, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\w+(?:,\\w+)*\\Z'), code='invalid', message='Enter only comma separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\w+(?:,\\w+)*\\Z'), code='invalid', message='Enter only comma separated by commas.')]),
        ),
    ]
