# Generated by Django 3.2 on 2022-05-12 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import glasses.utils.utils
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0006_alter_subcategory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=250, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.FloatField(verbose_name='selling price')),
                ('sku_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU Code')),
                ('frame_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Frame Size')),
                ('frame_width', models.FloatField(verbose_name='Frame Width')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color')),
                ('stocks', models.IntegerField(blank=True, default=0, null=True, verbose_name='number of stocks')),
                ('rating', models.FloatField(verbose_name='Ratings')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to=glasses.utils.utils.get_product_photo_path, width_field='width')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
