# Generated by Django 3.2 on 2022-06-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Dummy',
                'verbose_name_plural': 'Dummy',
            },
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photo_details', to='product.product'),
        ),
    ]
