# Generated by Django 3.2 on 2022-07-01 08:05

import blogs.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_passwordresetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_photo', null=True, upload_to=blogs.utils.utils.get_user_photo_random_filename, width_field='width_photo'),
        ),
    ]
