# Generated by Django 3.2 on 2022-05-05 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_productphoto_product'),
        ('order_place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('success', 'Success')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'COD'), ('upi', 'UPI'), ('card', 'Card')], default='cod', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=10, null=True, verbose_name='selling price'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.FloatField(default=10, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
