# Generated by Django 3.2 on 2022-05-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_place', '0005_alter_order_shipping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_product',
            field=models.IntegerField(default=0, null=True, verbose_name='Total Product'),
        ),
    ]
