# Generated by Django 3.2 on 2022-05-11 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import glasses.utils.utils
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_category_name_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(error_messages={'unique': 'A sub category with that name is already exists!!'}, max_length=50, unique=True, verbose_name='Subcategory name ')),
                ('slug', models.SlugField(blank=True, max_length=125, null=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, height_field='height_photo', null=True, upload_to=glasses.utils.utils.get_product_photo_path, width_field='width_photo')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
    ]
