# Generated by Django 3.2 on 2022-05-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import glasses.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0003_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category'},
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=glasses.utils.utils.get_product_photo_path, width_field='width'),
        ),
    ]
