# Generated by Django 3.2 on 2022-05-12 07:14

from django.db import migrations, models
import glasses.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=glasses.utils.utils.get_category_product_photo_path, width_field='width'),
        ),
    ]
