# Generated by Django 3.2 on 2022-05-16 12:23

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(error_messages={'unique': 'A user with that username is already exits.'}, help_text='Required. A 32 hexadecimal digits number as specified in RFC 4122.', unique=True, verbose_name='uuid')),
                ('username', models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. A 32 hexadecimal digits number as specified in RFC 4122', max_length=120, null=True, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with that eamil already exits.'}, max_length=254, null=True, unique=True, verbose_name='email Address')),
                ('is_email_verified', models.BooleanField(default=True, verbose_name='email verified')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('about', models.TextField(blank=True, max_length=1000, verbose_name='About me')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active.Unselected this instead of deleting accounts.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('last_user_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last activity')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone')),
                ('user_type', models.CharField(choices=[('user', 'User'), ('seller', 'Seller')], default='user', max_length=40)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
