# Generated by Django 3.2 on 2022-05-16 12:48

from django.db import migrations
import f_hlis.custom_auth.managers


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicationuser',
            managers=[
                ('objects', f_hlis.custom_auth.managers.ApplicationUserManager()),
            ],
        ),
    ]
