# Generated by Django 3.2 on 2022-05-16 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_applicationuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, error_messages={'unique': 'A user with that username is already exits.'}, help_text='Required. A 32 hexadecimal digits number as specified in RFC 4122.', unique=True, verbose_name='uuid'),
        ),
    ]
