# Generated by Django 3.2 on 2022-05-16 14:06

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_applicationuser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='soucial_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
